import streamlit as st
import random

# 都心型店舗メニュー
menu_city = [
    # にぎり
    { "name": "大切りまぐろ", "price": 130 },
    { "name": "まぐろステーキ", "price": 150 },
    { "name": "まぐろたたきねぎラー油", "price": 120 },
    { "name": "まぐろたたき盛り", "price": 120 },
    { "name": "まぐろたたき盛りシラチャ―ソースがけ", "price": 120 },
    { "name": "びん長まぐろ", "price": 110 },
    { "name": "びん長まぐろねぎラー油", "price": 110 },
    { "name": "びん長まぐろ山わさびのせ", "price": 110 },
    { "name": "びん長まぐろペッパーマヨ炙り", "price": 130 },
    { "name": "びん長まぐろマヨ炙り", "price": 130 },
    { "name": "まぐろはらも炙り", "price": 130 },
    { "name": "まぐろはらもペッパーマヨ炙り", "price": 130 },
    { "name": "まぐろはらもマヨ炙り", "price": 130 },
    { "name": "サーモン", "price": 120 },
    { "name": "オニオンサーモン", "price": 120 },
    { "name": "サーモンねぎラー油", "price": 120 },
    { "name": "サーモン・焼サーモン合い盛り", "price": 120 },
    { "name": "焼サーモン", "price": 120 },
    { "name": "大切りとろサーモン", "price": 130 },
    { "name": "大切りとろサーモン炙り", "price": 130 },
    { "name": "サーモンチーズ炙り（ホワイトチェダー）", "price": 130 },
    { "name": "サーモンペッパーマヨ炙り", "price": 130 },
    { "name": "サーモンマヨ炙り", "price": 130 },
    { "name": "サーモン揚げねぎラー油", "price": 120 },
    { "name": "いか", "price": 110 },
    { "name": "いかねぎラー油", "price": 110 },
    { "name": "いか明太マヨ", "price": 110 },
    { "name": "いか山わさびのせ", "price": 110 },
    { "name": "こういか", "price": 130 },
    { "name": "真だこ", "price": 130 },
    { "name": "えび", "price": 110 },
    { "name": "えび・たまご", "price": 110 },
    { "name": "えびねぎラー油", "price": 110 },
    { "name": "えび明太マヨ", "price": 110 },
    { "name": "アボカドシュリンプ", "price": 110 },
    { "name": "えびチーズ炙り（ホワイトチェダー）", "price": 130 },
    { "name": "えびペッパーマヨ炙り", "price": 130 },
    { "name": "えびマヨ炙り", "price": 130 },
    { "name": "甘えび", "price": 160 },
    { "name": "活け〆蒸しえび", "price": 110 },
    { "name": "えび天 天たれがけ", "price": 130 },
    { "name": "特大えびフライ", "price": 230 },
    { "name": "真鯛（活け〆）", "price": 210 },
    { "name": "えんがわ", "price": 160 },
    { "name": "あぶらかれい", "price": 110 },
    { "name": "煮あなご", "price": 110 },
    { "name": "ふわとろあなご", "price": 180 },
    { "name": "大切りうなぎ", "price": 180 },
    { "name": "国産いわし", "price": 110 },
    { "name": "こはだ", "price": 110 },
    { "name": "〆さば", "price": 110 },
    { "name": "大切り活け〆はまち", "price": 110 },
    { "name": "自家製上〆さば", "price": 210 },
    { "name": "自家製上〆さば炙り", "price": 210 },
    { "name": "北海道産ほたて", "price": 130 },
    { "name": "蒸しほたて", "price": 110 },
    { "name": "蒸しほたてチーズ炙り（ホワイトチェダー）", "price": 130 },
    { "name": "ほっき貝", "price": 130 },
    { "name": "つぶ貝", "price": 130 },
    { "name": "あかがい", "price": 110 },
    { "name": "白とり貝", "price": 110 },
    { "name": "生ハムサラダ", "price": 110 },
    { "name": "合鴨にぎり", "price": 110 },
    { "name": "ハンバーグ", "price": 130 },
    { "name": "チーズハンバーグ（ホワイトチェダー）", "price": 130 },
    { "name": "たまご", "price": 110 },
    { "name": "なす浅漬け（わさび風味）", "price": 110 },
    # 軍艦・巻物・いなり
    { "name": "まぐろたたきぐんかん", "price": 120 },
    { "name": "まぐたくぐんかん", "price": 120 },
    { "name": "まぐろたたき納豆", "price": 120 },
    { "name": "おくら納豆ぐんかん", "price": 110 },
    { "name": "いかおくら", "price": 110 },
    { "name": "納豆", "price": 110 },
    { "name": "あかいか明太ぐんかん", "price": 110 },
    { "name": "ししゃもっこ", "price": 110 },
    { "name": "いくら", "price": 150 },
    { "name": "サーモンアボカドぐんかん", "price": 130 },
    { "name": "えんがわぐんかん", "price": 110 },
    { "name": "海鮮ユッケ風", "price": 110 },
    { "name": "えびマヨ", "price": 130 },
    { "name": "ツナサラダ", "price": 110 },
    { "name": "コーン", "price": 110 },
    { "name": "ツナサラダ・コーン", "price": 110 },
    { "name": "シーフードサラダ", "price": 110 },
    { "name": "あんきも", "price": 150 },
    { "name": "かにみそ", "price": 110 },
    { "name": "いなり", "price": 110 },
    { "name": "いか昆布海苔包み", "price": 120 },
    { "name": "えんがわわさび海苔包み", "price": 120 },
    { "name": "つくね海苔包み", "price": 130 },
    { "name": "さばの押し寿司", "price": 120 },
    { "name": "とろさばの押し寿司", "price": 150 },
    { "name": "かっぱ巻揚げねぎラー油", "price": 130 },
    { "name": "鉄火巻揚げねぎラー油", "price": 150 },
    { "name": "鉄火巻", "price": 130 },
    { "name": "まぐたく巻", "price": 120 },
    { "name": "まぐろたたき巻", "price": 120 },
    { "name": "お新香巻", "price": 110 },
    { "name": "かっぱ巻", "price": 110 },
    { "name": "かんぴょう巻", "price": 110 },
    { "name": "納豆巻", "price": 110 },
    { "name": "鉄火巻山わさびのせ", "price": 130 },
    { "name": "まぐろたたき巻山わさびのせ", "price": 120 },
    { "name": "かっぱ巻山わさびのせ", "price": 110 },
    { "name": "かんぴょう巻山わさびのせ", "price": 110 },
    { "name": "納豆巻山わさびのせ", "price": 110 },
    { "name": "えび天巻", "price": 150 },
    # サイドメニュー
    { "name": "はまぐりの味噌汁", "price": 270 },
    { "name": "はまぐりの味噌汁　赤だし", "price": 270 },
    { "name": "青さ汁", "price": 130 },
    { "name": "青さ汁　赤だし", "price": 130 },
    { "name": "青さの茶碗蒸し", "price": 260 },
    { "name": "茶碗蒸し", "price": 260 },
    { "name": "春巻き", "price": 180 },
    { "name": "和風鶏もも唐揚げ", "price": 280 },
    { "name": "スティックチキン", "price": 190 },
    { "name": "フライドポテト", "price": 290 },
    { "name": "チーズポテト", "price": 300 },
    { "name": "醤油バターソースポテト", "price": 300 },
    { "name": "明太マヨポテト", "price": 300 },
    { "name": "明太オニオンサラダ", "price": 130 },
    { "name": "海鮮カルパッチョ", "price": 280 },
    { "name": "刺し盛り（真鯛活け〆）", "price": 300 },
    { "name": "刺し盛り5種", "price": 600 },
    { "name": "こだわり醤油ラーメン", "price": 400 },
    { "name": "チャーシュー麺", "price": 500 },
    { "name": "大阪発祥！かすうどん", "price": 390 },
    { "name": "たぬきうどん", "price": 170 },
    { "name": "えび天うどん", "price": 330 },
    { "name": "温玉明太うどん", "price": 330 },
    { "name": "きつねうどん", "price": 230 },
    { "name": "昆布うどん", "price": 230 },
    { "name": "背脂ラーメン", "price": 450 },
    # デザート・ドリンク
    { "name": "桜モンブラン", "price": 290 },
    { "name": "チョコレートパフェ", "price": 350 },
    { "name": "GODIVA®ミルクチョコレート", "price": 390 },
    { "name": "チョコレートケーキ", "price": 210 },
    { "name": "特製プリン", "price": 270 },
    { "name": "大学いも", "price": 150 },
    { "name": "紅茶のシフォンケーキ", "price": 270 },
    { "name": "ケーキセット(シフォンケーキ+コーヒー1つ)", "price": 460 },
    { "name": "北海道きなこのわらび餅", "price": 110 },
    { "name": "ソフトクリーム", "price": 290 },
    { "name": "ソフトクリーム チョコソース", "price": 290 },
    { "name": "コーラ　おもちゃ付き", "price": 180 },
    { "name": "コーラＷ　おもちゃ付き", "price": 310 },
    { "name": "ファンタオレンジ　おもちゃ付き", "price": 180 },
    { "name": "ファンタオレンジＷ　おもちゃ付き", "price": 310 },
    { "name": "メロンソーダ　おもちゃ付き", "price": 180 },
    { "name": "メロンソーダＷ　おもちゃ付き", "price": 310 },
    { "name": "グレープジュース　おもちゃ付き", "price": 180 },
    { "name": "グレープジュースW　おもちゃ付き", "price": 310 },
    { "name": "アップルジュース　おもちゃ付き", "price": 180 },
    { "name": "アップルジュースW　おもちゃ付き", "price": 310 },
    { "name": "カルピス　おもちゃ付き", "price": 180 },
    { "name": "カルピスW　おもちゃ付き", "price": 310 },
    { "name": "ウーロン茶　おもちゃ付き", "price": 180 },
    { "name": "ウーロン茶W　おもちゃ付き", "price": 310 },
    { "name": "Qooオレンジ　おもちゃ付き", "price": 180 },
    { "name": "QooオレンジW　おもちゃ付き", "price": 310 },
    { "name": "スペシャルコーヒー", "price": 200 },
    { "name": "スペシャルアイスコーヒー", "price": 200 },
    { "name": "スペシャルカフェラテ", "price": 230 },
    { "name": "スペシャルアイスカフェラテ", "price": 230 },
    { "name": "キリンビール晴れ風", "price": 390 },
    { "name": "一番搾り生ビール", "price": 600 },
    { "name": "グラスビール", "price": 380 },
    { "name": "スーパードライ生ビール", "price": 600 },
    { "name": "スーパードライグラスビール", "price": 380 },
    { "name": "一番搾り糖質0", "price": 420 },
    { "name": "氷零カロリミット（ノンアルコール）", "price": 380 },
    { "name": "生冷酒", "price": 480 },
    { "name": "ハイボール（ホワイトホース）", "price": 450 },
    { "name": "ハイボール（ブラックニッカ）", "price": 450 },
    { "name": "メガハイボール（ホワイトホース）", "price": 740 },
    { "name": "メガハイボール（ブラックニッカ）", "price": 740 },
    { "name": "レモンサワー", "price": 430 },
    { "name": "氷結®無糖レモン", "price": 430 },
    { "name": "梅酒（ロック）", "price": 420 },
    { "name": "芋焼酎（ロック）", "price": 500 },
    { "name": "芋焼酎（水割り）/（お湯割り）/（炭酸割り）", "price": 500 },
    { "name": "麦焼酎（ロック）", "price": 500 },
    { "name": "麦焼酎（水割り）/（お湯割り）/（炭酸割り）", "price": 500 },
]

# 超都心型店舗メニュー
menu_super_city =[
    {"name": "大切りまぐろ", "price": 170},
    {"name": "まぐろステーキ", "price": 190},
    {"name": "まぐろたたきねぎラー油", "price": 160},
    {"name": "まぐろたたき盛り", "price": 160},
    {"name": "まぐろたたき盛りシラチャ―ソースがけ", "price": 160},
    {"name": "びん長まぐろ", "price": 150},
    {"name": "びん長まぐろねぎラー油", "price": 150},
    {"name": "びん長まぐろ山わさびのせ", "price": 150},
    {"name": "びん長まぐろペッパーマヨ炙り", "price": 170},
    {"name": "びん長まぐろマヨ炙り", "price": 170},
    {"name": "サーモン", "price": 160},
    {"name": "オニオンサーモン", "price": 160},
    {"name": "サーモンねぎラー油", "price": 160},
    {"name": "サーモン・焼サーモン合い盛り", "price": 160},
    {"name": "焼サーモン", "price": 160},
    {"name": "大切りとろサーモン", "price": 170},
    {"name": "大切りとろサーモン炙り", "price": 170},
    {"name": "サーモンチーズ炙り（ホワイトチェダー）", "price": 170},
    {"name": "サーモンペッパーマヨ炙り", "price": 170},
    {"name": "サーモンマヨ炙り", "price": 170},
    {"name": "サーモン揚げねぎラー油", "price": 160},
    {"name": "いか", "price": 150},
    {"name": "いかねぎラー油", "price": 150},
    {"name": "いか明太マヨ", "price": 150},
    {"name": "いか山わさびのせ", "price": 150},
    {"name": "こういか", "price": 170},
    {"name": "真だこ", "price": 170},
    {"name": "えび", "price": 150},
    {"name": "えび・たまご", "price": 150},
    {"name": "えびねぎラー油", "price": 150},
    {"name": "えび明太マヨ", "price": 150},
    {"name": "アボカドシュリンプ", "price": 150},
    {"name": "えびチーズ炙り（ホワイトチェダー）", "price": 170},
    {"name": "えびペッパーマヨ炙り", "price": 170},
    {"name": "えびマヨ炙り", "price": 170},
    {"name": "甘えび", "price": 200},
    {"name": "活け〆蒸しえび", "price": 150},
    {"name": "えび天 天たれがけ", "price": 170},
    {"name": "えんがわ", "price": 200},
    {"name": "あぶらかれい", "price": 150},
    {"name": "煮あなご", "price": 150},
    {"name": "ふわとろあなご", "price": 220},
    {"name": "大切りうなぎ", "price": 220},
    {"name": "国産いわし", "price": 150},
    {"name": "こはだ", "price": 150},
    {"name": "〆さば", "price": 150},
    {"name": "大切り活け〆はまち", "price": 150},
    {"name": "北海道産ほたて", "price": 170},
    {"name": "蒸しほたて", "price": 150},
    {"name": "蒸しほたてチーズ炙り（ホワイトチェダー）", "price": 170},
    {"name": "ほっき貝", "price": 170},
    {"name": "つぶ貝", "price": 170},
    {"name": "あかがい", "price": 150},
    {"name": "白とり貝", "price": 150},
    {"name": "生ハムサラダ", "price": 150},
    {"name": "合鴨にぎり", "price": 150},
    {"name": "ハンバーグ", "price": 170},
    {"name": "チーズハンバーグ（ホワイトチェダー）", "price": 170},
    {"name": "たまご", "price": 150},
    {"name": "なす浅漬け（わさび風味）", "price": 150},
    {"name": "まぐろたたきぐんかん", "price": 160},
    {"name": "まぐたくぐんかん", "price": 160},
    {"name": "まぐろたたき納豆", "price": 160},
    {"name": "おくら納豆ぐんかん", "price": 150},
    {"name": "いかおくら", "price": 150},
    {"name": "納豆", "price": 150},
    {"name": "あかいか明太ぐんかん", "price": 150},
    {"name": "ししゃもっこ", "price": 150},
    {"name": "いくら", "price": 190},
    {"name": "サーモンアボカドぐんかん", "price": 170},
    {"name": "えんがわぐんかん", "price": 150},
    {"name": "海鮮ユッケ風", "price": 150},
    {"name": "えびマヨ", "price": 170},
    {"name": "ツナサラダ", "price": 150},
    {"name": "コーン", "price": 150},
    {"name": "ツナサラダ・コーン", "price": 150},
    {"name": "シーフードサラダ", "price": 150},
    {"name": "あんきも", "price": 190},
    {"name": "かにみそ", "price": 150},
    {"name": "いなり", "price": 150},
    {"name": "いか昆布海苔包み", "price": 160},
    {"name": "えんがわわさび海苔包み", "price": 160},
    {"name": "つくね海苔包み", "price": 170},
    {"name": "とろさばの押し寿司", "price": 190},
    {"name": "かっぱ巻揚げねぎラー油", "price": 170},
    {"name": "鉄火巻揚げねぎラー油", "price": 190},
    {"name": "鉄火巻", "price": 170},
    {"name": "まぐたく巻", "price": 160},
    {"name": "まぐろたたき巻", "price": 160},
    {"name": "お新香巻", "price": 150},
    {"name": "かっぱ巻", "price": 150},
    {"name": "かんぴょう巻", "price": 150},
    {"name": "納豆巻", "price": 150},
    {"name": "えび天巻", "price": 190},
    {"name": "はまぐりの味噌汁", "price": 310},
    {"name": "青さ汁", "price": 170},
    {"name": "青さの茶碗蒸し", "price": 300},
    {"name": "茶碗蒸し", "price": 300},
    {"name": "春巻き", "price": 220},
    {"name": "和風鶏もも唐揚げ", "price": 320},
    {"name": "スティックチキン", "price": 230},
    {"name": "フライドポテト", "price": 330},
    {"name": "チーズポテト", "price": 350},
    {"name": "醤油バターソースポテト", "price": 350},
    {"name": "明太マヨポテト", "price": 350},
    {"name": "明太オニオンサラダ", "price": 170},
    {"name": "海鮮カルパッチョ", "price": 320},
    {"name": "刺し盛り5種", "price": 660},
    {"name": "こだわり醤油ラーメン", "price": 440},
    {"name": "チャーシュー麺", "price": 540},
    {"name": "大阪発祥！かすうどん", "price": 430},
    {"name": "たぬきうどん", "price": 210},
    {"name": "えび天うどん", "price": 370},
    {"name": "温玉明太うどん", "price": 370},
    {"name": "桜モンブラン", "price": 330},
    {"name": "チョコレートパフェ", "price": 390},
    {"name": "GODIVA®ミルクチョコレート", "price": 430},
    {"name": "チョコレートケーキ", "price": 250},
    {"name": "特製プリン", "price": 310},
    {"name": "大学いも", "price": 190},
    {"name": "紅茶のシフォンケーキ", "price": 310},
    {"name": "ケーキセット(シフォンケーキ+コーヒー1つ)", "price": 500},
    {"name": "北海道きなこのわらび餅", "price": 150},
    {"name": "ソフトクリーム", "price": 330},
    {"name": "ソフトクリーム チョコソース", "price": 330},
    {"name": "コーラ　おもちゃ付き", "price": 190},
    {"name": "コーラＷ　おもちゃ付き", "price": 330},
    {"name": "メロンソーダ　おもちゃ付き", "price": 190},
    {"name": "メロンソーダＷ　おもちゃ付き", "price": 330},
    {"name": "グレープジュース　おもちゃ付き", "price": 190},
    {"name": "グレープジュースW　おもちゃ付き", "price": 330},
    {"name": "アップルジュース　おもちゃ付き", "price": 190},
    {"name": "アップルジュースW　おもちゃ付き", "price": 330},
    {"name": "カルピス　おもちゃ付き", "price": 190},
    {"name": "カルピスW　おもちゃ付き", "price": 330},
    {"name": "ウーロン茶　おもちゃ付き", "price": 190},
    {"name": "ウーロン茶W　おもちゃ付き", "price": 330},
    {"name": "Qooオレンジ　おもちゃ付き", "price": 190},
    {"name": "QooオレンジW　おもちゃ付き", "price": 330},
    {"name": "スペシャルコーヒー", "price": 200},
    {"name": "スペシャルアイスコーヒー", "price": 200},
    {"name": "スペシャルカフェラテ", "price": 230},
    {"name": "スペシャルアイスカフェラテ", "price": 230},
    {"name": "キリンビール晴れ風", "price": 430},
    {"name": "一番搾り生ビール", "price": 640},
    {"name": "グラスビール", "price": 420},
    {"name": "一番搾り糖質0", "price": 460},
    {"name": "氷零カロリミット（ノンアルコール）", "price": 420},
    {"name": "生冷酒", "price": 520},
    {"name": "ハイボール（ホワイトホース）", "price": 490},
    {"name": "メガハイボール（ホワイトホース）", "price": 780},
    {"name": "レモンサワー", "price": 470},
    {"name": "氷結®無糖レモン", "price": 470},
    {"name": "梅酒（ロック）", "price": 460},
    {"name": "芋焼酎（ロック）", "price": 540},
    {"name": "芋焼酎（水割り）/（お湯割り）/（炭酸割り）", "price": 540},
    {"name": "麦焼酎（ロック）", "price": 540},
    {"name": "麦焼酎（水割り）/（お湯割り）/（炭酸割り）", "price": 540}
] 

def n_yen_gacha(menu, target_price):
    result = []
    total = 0
    tries = 0

    while total < target_price and tries < 1000:
        item = random.choice(menu)
        if total + item["price"] <= target_price:
            result.append(item)
            total += item["price"]
        tries += 1
    return result, total

# UI
st.title("🍣 魚べいN円ガチャ")

menu_type = st.selectbox("店舗を選んでください", ["都心型店舗", "超都心型店舗"])
budget = st.selectbox("予算を選んでください", [500, 1000, 1500])

if menu_type == "都心型店舗":
    selected_menu = menu_city
else:
    selected_menu = menu_super_city

if st.button("ガチャを回す！"):
    items, total = n_yen_gacha(selected_menu, budget)
    st.subheader("🎯 結果")
    for item in items:
        st.write(f"・{item['name']}（{item['price']}円）")
    st.write(f"**合計：{total}円**")
